project:
  type: website
  output-dir: .

website:
  title: "Mitchell Heaton - Data Science Portfolio"
  description: "A showcase of my data science projects and learning journey"
  
  navbar:
    background: primary
    brand: "Mitchell Heaton"
          
    right:
      - icon: github
        href: https://github.com/mitchster21
      - icon: linkedin
        href: https://linkedin.com/in/mitchell-heaton-778354333

  sidebar:
    - title: "Projects"
      contents:
        - index.html

format:
  html:
    theme: cosmo
    toc: true
    code-fold: true
    code-tools: true
    css: styles.css
